# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Appforseii2526.Api

on:
  push:
    branches:
      - development
    paths:
      - 'src/AppForSEII2526.API**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      API: ./src/AppForSEII2526.API/AppForSEII2526.API.csproj
      UT: ./test/AppForSEII2526.UT/AppForSEII2526.UT.csproj

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies        
        run: |  
          dotnet restore ${{ env.API }} 
          dotnet restore ${{ env.UT }} 

      - name: Build with dotnet
        run: |
          dotnet build ${{ env.API }}  --configuration Release --no-restore
          dotnet build ${{ env.UT }}

      #- name: Run unit test with report
      #  run: dotnet test ${{ env.UT }}
        
      - name: dotnet publish
        run: dotnet publish ${{ env.API }}  -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DCEBD377844041DFAB2E64181F75A30A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B8D37A77E0EA4DDDB9702995ED87A874 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F10C1B724F674399A949A61B962BF3EF }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appforseii2526api'
          slot-name: 'Production'
          package: .

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D431DCDCED3A4E958AA16992E05EDA40}}
